// Trains the learned control policy and writes src/learned-policy.ts.
//   npm run train -- [episodes] [minutes]
import { writeFileSync } from 'node:fs';
import { train } from '../src/rl';

const episodes = Number(process.argv[2] ?? 120);
const minutes = Number(process.argv[3] ?? 6);
const started = Date.now();
const q = train({
  episodes,
  minutes,
  seed: 1,
  onEpisode: (e, mean) => {
    if (e % 10 === 0)
      console.log(`episode ${e}/${episodes}: mean queue ${mean.toFixed(2)} (${((Date.now() - started) / 1000).toFixed(0)} s)`);
  },
});
const visited = q.filter(([a, b]) => a !== 0 || b !== 0).length;
const rows = q.map(([a, b]) => `  [${a.toFixed(3)}, ${b.toFixed(3)}],`).join('\n');
writeFileSync(
  new URL('../src/learned-policy.ts', import.meta.url),
  `// Q-table of the learned control policy: [keep, switch] values per state (see controller.ts
// encodeState). Generated by \`npm run train\` (${episodes} episodes of ${minutes} min); all zeros means
// "not trained yet", and the policy then falls back to the longest-queue rule.
export const LEARNED_Q: number[][] = [
${rows}
];
`,
);
console.log(`wrote ${q.length} states, ${visited} visited`);
